In [1]:
import numpy as np 

1) create array using numpy 

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


2) create array of zeros :

In [5]:
zero_array = np.zeros((2,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]]


3) create array of ones :

In [ ]:
ones_a = np.ones((2,3))
print(ones_a)


[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
range_A = np.arange(1,12)
print(range_A)

line_array = np.linspace(0,1,5)
print(line_array)

random = np.random.rand(2,3)
print(random)

[ 1  2  3  4  5  6  7  8  9 10 11]
[0.   0.25 0.5  0.75 1.  ]
[[0.83652543 0.37404321 0.3458502 ]
 [0.93945627 0.83838311 0.64470194]]


## attributes ,indexing and slicing 
Array attributes provide information about the array,Indexing and slicing are used to access specific values, rows, or columns

In [18]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(matrix.shape)
print("dimensions:",matrix.ndim)
print("size of matrix = ",matrix.size)
print("Data type :" ,matrix.dtype)
print(matrix[1,2])
print("second element")
print(matrix[:,1])
print("last row ")
print((matrix[-1,:]))

(3, 3)
dimensions: 2
size of matrix =  9
Data type : int64
6
second element
[2 5 8]
last row 
[7 8 9]


## vectorized operation & Boolean Masking 
vectorized operations applay calculation directly to all array elements without using loops , Boolean masking filters values based on a condition 

In [24]:
arr = np.array([1,10,7,3])

sum = ("addition",arr+arr) 
print(sum)

('addition', array([ 2, 20, 14,  6]))


In [25]:
mult = (arr*arr)# multiply elements by element
print(mult)

[  1 100  49   9]


In [27]:
print("mean =",arr.mean())

mean = 5.25


In [28]:
print("max =",arr.max())

max = 10


In [29]:
print("minimum : ", arr.min())

minimum :  1


In [31]:
n =(arr[arr>5])# values greater than 5
print(n)

[10  7]


## Broadcasting
allows numpy to perform operation between arrays with compatible shapes 

In [33]:
x = np.array([
[1,2,3],
[4,7,9]

])
row = np.array([5,4,10])
print(x + row)
print("          ")
print(matrix +2)

[[ 6  6 13]
 [ 9 11 19]]
          
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## Hand-on lab 

Task1 :
Create a 2D array of shape (4, 4) filled with values 1-16 and print its shape and dtype.

In [37]:
a = np.arange(1,17).reshape(4,4)
print(a)
print("shape:",a.shape)
print("data type :" ,a.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
shape: (4, 4)
data type : int64


Task2:
 extract the second column and the last row.

In [40]:
second_col = a[:,1]
print("second col",second_col)
last_row = a[-1,:]
print("last row ",last_row)


second col [ 2  6 10 14]
last row  [13 14 15 16]


Task3 :
 Use a boolean mask to select all values greater than the array's mean.

In [43]:
mean_val = a.mean()
print("mean",mean_val)
val = a[a>mean_val]
print("values greater than the array's mean",val)

mean 8.5
values greater than the array's mean [ 9 10 11 12 13 14 15 16]


Task4:
 Add a 1D row array to every row of a 2D array using broadcasting, and verify the result manually

In [44]:
row = np.array([10, 20, 30, 40])
result = a + row

print("Result:")
print(result)

print("Manual :")
print(a[0], "+", row, "=", a[0] + row)
print(a[1], "+", row, "=", a[1] + row)
print(a[2], "+", row, "=", a[2] + row)
print(a[3], "+", row, "=", a[3] + row)

Result:
[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]
 [23 34 45 56]]
Manual :
[1 2 3 4] + [10 20 30 40] = [11 22 33 44]
[5 6 7 8] + [10 20 30 40] = [15 26 37 48]
[ 9 10 11 12] + [10 20 30 40] = [19 30 41 52]
[13 14 15 16] + [10 20 30 40] = [23 34 45 56]
