# Day3  - Linear Algebra for Machine Learinig
Linear Algebra is used in Ml to represent data and make calculations 
it include vectors,matrices ,dot product ,and matrix multiplication

## import numpy 

In [1]:
import numpy as np 


## Vectors 
A vector is a one-dimensional array ,it can represent one student with different feature 

In [ ]:
student = np.array([20,6,90]) ## age = 20 , study hours = 6 , exam score =90
print(student)
print("shape:",student.shape)

[20  6 90]
shape: (3,)


## Matrices 
A matrix is a group of vectors 
each row represents one student , and each column represents one feature 

In [8]:
student = np.array([
    [20,6,90],
                   [22,4,85],
                   [21,8,95]])
print(student)
print("shape",student.shape)

[[20  6 90]
 [22  4 85]
 [21  8 95]]
shape (3, 3)


the matrix contains 3 students 
columns : age,study hours , exam score .
The shape (3,3)

## Dot product 
The dot product (or scalar product) of two vectors is a way of multiplying vectors that results in a scalar (number). This operation, often symbolized by a centered dot, is dependent on the length of both vectors and the angle between them

In [9]:
a = np.array([4,6,9])
b = np.array([2,3,4])
result = np.dot(a,b)
print(result)

62


## Matrix Multiplication 
 multiplication can be used to calculate results for more than one student at the same time

## RULE 
(M X N) X (N X P)

In [10]:
Student =  np.array([[4,80],[7,60],[8,95]])
w = np.array([2,1.5])
r = Student@w
print(r)

[128.  104.  158.5]


For the first student 
(4 x 2 ) + (80 X 1.5)
= 128

## Hand-on lab 
### Step1: create a matrix with three samples 

In [11]:
data = np.array([[5,60],[4,90],[3,80]])
print(data)
print("shape",data.shape)

[[ 5 60]
 [ 4 90]
 [ 3 80]]
shape (3, 2)


the matrix have 3 students and 2 features 


### Step2 :calculate the dot product 


In [12]:
sample =data[0]
weight =np.array([2,1.5])
result = np.dot(sample,weight)
print(result)

100.0


by hand :
5 X 2 + 60 x 1.5 

## step3 
predict all students 


In [13]:
predection = data@weight
print(predection)

[100. 143. 126.]


the code calculate the result for all students at the same time 

## step 4 

creat two arrays with shapes that do not match

In [14]:
a = np.array([[1,2],[3,4]])
b = np.array([1,2,3])
print(a@b)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

the error happend because the inner dimensions do not match 
a has 2 columns , b has 3 values  

correct exmaple :

In [15]:
b = np.array([1,2])
print(a@b)


[ 5 11]


the error was fixed by changing b to have 2 values 